---
title: Bureaucracy Profile
output: 
  pdf_document
header-includes:
      - \usepackage{xcolor,sectsty}
      - \usepackage[framemethod=tikz]{mdframed}
      - \pagestyle{empty}
      - \renewcommand{\familydefault}{\sfdefault}
      - \definecolor{titlecolor}{RGB}{82,150,165}
      - \definecolor{countrynamecolor}{RGB}{253,236,217}
      - \definecolor{sectionbox}{RGB}{205,179,155}
      - \definecolor{sectiontitle}{RGB}{45,82,90}
      - \newmdenv[	linecolor= titlecolor,	innerleftmargin= 10pt,innerrightmargin	= 10pt, innertopmargin = 15pt,	innerbottommargin	= 5pt,	backgroundcolor = titlecolor]{titlebox}
      - \newmdenv[linecolor = titlecolor,innerleftmargin = 10pt,innerrightmargin	= 10pt,innertopmargin	 	= 7pt,innerbottommargin	= 10pt,backgroundcolor		= titlecolor]{countrynamebox}
      - \newmdenv[linecolor			= sectionbox,innerleftmargin		= 0pt, innerrightmargin	= 10pt,innertopmargin		= 10pt,innerbottommargin	= 10pt, backgroundcolor		= sectionbox]{sectionbox}
      - \makeatletter\renewcommand{\maketitle}{\bgroup\setlength{\parindent}{0pt}\begin{flushleft}\begin{titlebox}\Huge\color{white}\textbf{\@title}\@author\end{titlebox}\end{flushleft}\egroup}
      - \makeatother
      - \subsectionfont{\color{titlecolor}}
      - \makeatletter
params:
  selected_country: NA
---

```{r setup, include=FALSE}
# Never print codes or warnings
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(fig.width=10)
knitr::opts_chunk$set(fig.height=5)
knitr::opts_chunk$set(fig.show='hold')
knitr::opts_chunk$set(fig.align='center')
```

```{r, include = F}
# 1 Set Initial configs ===============================================================

  # 1.1 Load packages --------------------------------------------------------------
  library(ggplot2)
  library(ggrepel)
  library(viridis)
  library(plotly)
  library(gridExtra)

  # 1.2 Create theme that will be used for graphs -----------------------------------
  my_theme <- theme_classic() +
    theme(legend.position = "bottom",
          legend.title = (element_blank()),
          plot.title = element_text(hjust = .5))

  # 1.3 Load the data ---------------------------------------------------------------
  
  # Load full data set
  wwbi <- read.csv("data.csv", header = T,
                   stringsAsFactors = F)

  # If the country selected is not Thailand, we will not consider it for plot 7,
  # It is an outlier and distorts the graph
  plot7_data <- subset(wwbi, ccode!="THA")
  
  
# 2 Calculate section switches ======================================================
# Some countries will have missing variables. We need to know what variables we have
# so no empty sections will be displayed, and figures are correctly aligned
# ================================================================================= #
  
  # 2.1 Test if Wage bill section will be displayed and save that in an object ------
  
    # 2.1.1 Is the first plot going to be created? -----------------------------------
    wb_gdp <- !is.na(wwbi$wage_gdp[wwbi$countryname == params$selected_country])
    
    # 2.1.2 Is the second plot going to be created? ----------------------------------
    wb_exp <- !is.na(wwbi$wage_x[wwbi$countryname == params$selected_country])
      
    # 2.1.3 If any plots exist, create section ---------------------------------------
    wagebill <- (wb_gdp | wb_exp)
```

`r paste0("\\begin{countrynamebox}\\flushleft\\huge\\color{countrynamecolor}",params$selected_country,"\\end{countrynamebox}")`
`r if(wagebill){"\\vspace{15pt}\\begin{sectionbox}\\center\\Large\\color{sectiontitle}\\textbf{Wage bill}\\end{sectionbox}"}`

```{r, eval = wagebill}
# Add graphs for wage bill section

  # Create GDP graph (if we have that information)  
  if (wb_gdp) {
    wb_gdp_plot <- 
      ggplot() +
        geom_smooth(data = wwbi,
                    aes(x = lngdppc ,
                        y = wage_gdp), method='lm', formula=y~x, se=FALSE,color="grey", linetype="dashed") +
        geom_point(data = wwbi,
                   aes(x = lngdppc ,
                       y = wage_gdp,
                       color = region)) +
        geom_point(data = wwbi[wwbi$countryname == params$selected_country, ],
                   aes(x = lngdppc ,
                       y = wage_gdp),
                   color = "red", size=3) +
        geom_label_repel(data = wwbi[wwbi$countryname == params$selected_country, ],
                         aes(x = lngdppc ,
                             y = wage_gdp, 
                             label=paste0(countryname,":", round(wage_gdp, 0), "% ")),
                         color = "red") +
        ylab("Wage bill(%)") + xlab("Log of GDP per capita") +
        ggtitle("Wage bill as % of GDP") +
        scale_color_viridis(discrete=TRUE)+
        my_theme
  }
  
  # Create Expenditure graph (if we have that information)  
  if (wb_exp) {
    wb_exp_plot <- 
      ggplot() +
        geom_smooth(data = wwbi,
                    aes(x = lngdppc ,
                        y = wage_x), method='lm', formula=y~x, se=FALSE,color="grey", linetype="dashed") +
        geom_point(data = wwbi,
                   aes(x = lngdppc ,
                       y = wage_x,
                       color = region)) +
        geom_point(data = wwbi[wwbi$countryname == params$selected_country, ],
                   aes(x = lngdppc ,
                       y = wage_x),
                   color = "red", size=3) +
        geom_label_repel(data = wwbi[wwbi$countryname == params$selected_country, ],
                         aes(x = lngdppc ,
                             y = wage_x, 
                             label=paste0(countryname,":", round(wage_x, 0), "% ")),
                         color = "red") +
        ylab("Wage bill(%)") + xlab("Log of GDP per capita") +
        ggtitle("Wage bill as % of expenditures") +
        scale_color_viridis(discrete=TRUE)+
        my_theme
  }

  # Print graphs to report -- only print if the variables exist
  if (wb_gdp & wb_exp) {
    grid.arrange(wb_gdp_plot, wb_exp_plot, ncol=2)
  } else if (wb_gdp & !wb_exp) {
    wb_gdp_plot
  } else if (!wb_gdp & wb_exp) {
    wb_exp_plot
  }
```
